export const applicationTypeEnum = {
SAMADHAN_COMPLAINTS : 100001
}

export const categoryTypeEnum = {
    INDIVIDUAL_COMPLAINT_WAGES_WEEKLY_PERIOD_AMOUNT : 2009,
    INDIVIDUAL_COMPLAINT_WAGES_WEEKLY : 2010,

    INDIVIDUAL_COMPLAINT_WORKING_OVERTIME : 2011,
    INDIVIDUAL_COMPLAINT_WORKING_OVERTIME_PERIOD_AMOUNT  : 2012,

    INDIVIDUAL_COMPLAINT_WAGES_NOT_PAID : 2013,
    INDIVIDUAL_COMPLAINT_WAGES_NOT_PAID_PERIOD_AMOUNT  : 2014,

    INDIVIDUAL_COMPLAINT_WAGES_UNAUTHDED : 2015,
    INDIVIDUAL_COMPLAINT_WAGES_UNAUTHDED_PERIOD_AMOUNT  : 2016,

    INDIVIDUAL_COMPLAINT_NON_PAY_BONUS : 2017,
    INDIVIDUAL_COMPLAINT_NON_PAY_BONUS_PERIOD_AMOUNT  :  2018,

    INDIVIDUAL_COMPLAINT_REC_OF_MON_GEN_DETAILS : 2019,

    INDIVIDUAL_COMPLAINT_REC_OF_MON_SETTLEMENT_DETAILS : 2020,

    INDIVIDUAL_COMPLAINT_REC_OF_MON_AWARD_DETAILS : 2021,

    INDIVIDUAL_COMPLAINT_REC_OF_MON_NOTICE_PAY_DETAILS : 2022,


    INDIVIDUAL_COMPLAINT_REC_OF_MON_RETRENCHMENT_DETAILS : 2023,


    INDIVIDUAL_COMPLAINT_REC_OF_MON_LAY_OFF_DETAILS : 2024,

    INDIVIDUAL_COMPLAINT_REC_OF_MON_LAY_OFF_COMPDETAILS : 2025,

    INDIVIDUAL_COMPLAINT_REC_OF_MON_DUE : 2026,



}

export enum SettlementTypeEnum {
  Bipartite = 1,
  Tripartite = 2
}