export const applicationTypeEnum = {
SAMADHAN_COMPLAINTS : 100001
}

export const categoryTypeEnum = {
    INDIVIDUAL_COMPLAINT_WAGES_WEEKLY_PERIOD_AMOUNT : 2009,
    INDIVIDUAL_COMPLAINT_WAGES_WEEKLY : 2010,

    INDIVIDUAL_COMPLAINT_WORKING_OVERTIME : 2011,
    INDIVIDUAL_COMPLAINT_WORKING_OVERTIME_PERIOD_AMOUNT  : 2012,
}